apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flight-search-data
  namespace: flight-search
  labels:
    app: flight-search
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
