apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: booking-api-data
  namespace: booking-api
  labels:
    app.kubernetes.io/name: booking-api
    cost-center: booking-engine
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
