apiVersion: v1
kind: Service
metadata:
  name: flight-search-service
  namespace: airline
  labels:
    app: flight-search
spec:
  selector:
    app: flight-search
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
