apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payment-logs
  namespace: payment
  labels:
    environment: prod
    owner: payments-team
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
