apiVersion: v1
kind: Service
metadata:
  name: payment-processor
  namespace: payment
  labels:
    environment: prod
    owner: payments-team
spec:
  selector:
    app: payment
  ports:
  - port: 8443
    targetPort: 8443
  type: ClusterIP
