{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8-finops-agent.serviceAccountName" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "k8-finops-agent.labels" . | nindent 4 }}
{{- end }}
